name: weight_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-81.0.dev <3.0.0"

dependencies:
  auth_service: ^0.0.2
  cloud_firestore: ^3.4.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  flutter_riverpod: 2.0.0-dev.9
  go_router: 3.1.0
  http: ^0.13.4

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
